FROM node:lts-alpine as build-stage
WORKDIR /app
COPY . ./

# production stage
FROM nginx:stable-alpine as production-stage
COPY /app /usr/share/nginx/html
COPY /app/nginx/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]